name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            .npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Validation step
        run: echo "Running validation..."

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Running tests..."

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: echo "Building project..."

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Release step
        run: echo "Releasing version..."

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Deploy step
        run: echo "Deploying..."
